### ISSUE TITLE
Error w/ MPIScheduler Build

### ISSUE THREAD

**Issue by brantfaircloth** [BenoitMorel/multi-raxml#58]
Hi benoit,

I'm running into a cmake error during the MPIScheduler build process (run from the normal `./install.sh` script).  The gist of the issue is that I'm receiving the following warning:

```
-- Detecting CXX compile features - done
WARNING: Target "cmTC_7db5a" requests linking to directory "/usr/local/compilers/Intel/parallel_studio_xe_2018.0/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib/release_mt".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cmTC_7db5a" requests linking to directory "/usr/local/compilers/Intel/parallel_studio_xe_2018.0/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Could NOT find MPI_C (missing: MPI_C_WORKS)
WARNING: Target "cmTC_1ddb9" requests linking to directory "/usr/local/compilers/Intel/parallel_studio_xe_2018.0/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib/release_mt".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cmTC_1ddb9" requests linking to directory "/usr/local/compilers/Intel/parallel_studio_xe_2018.0/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
```

This appears to result in MPIScheduler failing to build for MPI (OpenMP looks ok).  I compiled with the following loaded:

```
cmake version 3.15.0-rc4
gcc/6.4.0
intel/2018.0
impi/2018.0.128/intel64
```

Thanks in advance,
b

**Comment by BenoitMorel** [comment]
Hi Brant, 

Thanks for your report. I managed to reproduce your issue with impi, and I am still working on finding a solution.
Do you have any other available MPI implementation? (for instance OpenMPI)

Benoit

**Comment by BenoitMorel** [comment]
You can solve the cmake issue by using an older cmake version (cmake 3.5 works on our cluster)
See: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=CCPEM;9797b334.1808

Alternatively, compiling with OpenMPI instead of Intel MPI should also work.

Benoit

**Comment by brantfaircloth** [comment]
I downgraded to cmake 3.5 and all worked well.
