### ISSUE TITLE
make -j 40

### ISSUE THREAD

**Issue by brantfaircloth** [BenoitMorel/multi-raxml#59]
Hi Benoit,

Posting as a separate issue... I also noticed that `install.sh` seems to specify `make -j 40` by default.  I wasn't sure if this was intentional.

-b

**Comment by BenoitMorel** [comment]
Hi Brant,

You are right, this was not intentional. But we just discussed it and it might actually be good like that, even if you have less than 40 cores. Did you observe any compilation slowdown because of that? I could also just let the user decide the number of cores.

Benoit

**Comment by brantfaircloth** [comment]
My only concern is that on a shared system where folks may be compiling on the login node (which is reasonably common, I think), the `make -j 40` could cause problems for other users due to resource consumption by the compilation process.

**Comment by BenoitMorel** [comment]
Good point :-)
I reduced to 4 (I think it's reasonable for login nodes) , and you can specify the number of cores with `./install.sh number_of_cores`
Thanks a lot for the suggestion!
