### ISSUE TITLE
Error parsing the cmd

### ISSUE THREAD

**Issue by weedcentipede** [BenoitMorel/multi-raxml#60]
Hi, I'm getting the following error while running Pargenes, 
```
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
/home/larteag7/apps/ParGenes/pargenes/pargenes.py: line 4: args: command not found
/home/larteag7/apps/ParGenes/pargenes/pargenes.py: line 5: syntax error near unexpected token `"--scheduler"'
/home/larteag7/apps/ParGenes/pargenes/pargenes.py: line 5: `args.append("--scheduler")'
```
I imported some python modules and some mpi modules but that didn't help, 
What is the error related with? 
How can I solved it?

cheers, 
Luis Alfonso.

**Comment by BenoitMorel** [comment]
Hi Luis,

Could you please give me the whole command line you used to start ParGenes?
Cheers,

Benoit

**Comment by weedcentipede** [comment]
Hi Benoit, 

This is the command line ```pargenes.py -a csds -o trees -c 16 -d nt --use-modeltest```

Cheers, 
Luis Alfonso.

**Comment by BenoitMorel** [comment]
You should call it with python
`python pargenes.py -a csds -o trees -c 16 -d nt --use-modeltest `

I will soon add a shebang line in the script, such that you can call the script without "python"

**Comment by BenoitMorel** [comment]
I am closing this. If the problem was not solved, please reopen!
