### ISSUE TITLE
Conda package for ParGenes

### ISSUE THREAD

**Issue by dansondergaard** [BenoitMorel/multi-raxml#62]
Hi,

A lot of people are now using Conda to install and manage scientific software. It would be great to have a Conda package (perhaps on Bioconda) to installing ParGenes. This would also solve #53.

Thanks!

**Comment by BenoitMorel** [comment]
Hi,

thanks a lot for the suggestion, this sounds like a good idea. I won't be able to work on that in the next few weeks, but I will consider this carefully as soon as possible.

Benoit

**Comment by probstrodolfo** [comment]
Hi Benoit,

I was wondering if you have any news on the conda package for your program?

Thanks!

**Comment by BenoitMorel** [comment]
Thanks for reminding me of this. Yes, this got posponed several times but
it's still somewhere in the top of my todolist. I already started working
on it but there are a few issues than I need to fix. I will have one more
look in the next two weeks.

Benoit

Le ven. 26 juin 2020 à 02:01, probstrodolfo <notifications@github.com> a
écrit :

**Comment by probstrodolfo** [comment]
Excellent, appreciate the feedback, Benoit.

Best,

**Comment by herber4** [comment]
has there been any progress made on this?

**Comment by BenoitMorel** [comment]
Dear all,

sorry for all the delay in answering/doing the work. I have been working the last days on the ParGenes bioconda package. There have been many issues, but I hope I can get a proper package before the end of the year...

**Comment by BenoitMorel** [comment]
The bioconda pargenes package is now available! https://anaconda.org/bioconda/pargenes
I only managed to make it work on linux. I let the ticket opened since I am still trying to make it work on macos.

**Comment by BenoitMorel** [comment]
I am closing this issue. I haven't managed to make the package pass the conda pipeline on macos...

**Comment by davidomartinez** [comment]
Hi Benoit:

Thanks again for developing Pargenes. It makes life much easier for dealing with Astral. I am currently trying to install it in a Linux cluster, but I am getting a rather non-informativeerror message, copied below. Any ideas? Thanks in advance.

(base) (BUSTER)xxx@xxx:~$ conda install -c bioconda pargenes
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by davidomartinez** [comment]
As a continuation of the previous message, when I try to install it myself in the cluster, I get another error:

(base) (BUSTER)davidomartinez@minos:~/ParGenes$ ./install.sh
Running from /storage/plzen1/home/davidomartinez/ParGenes
Installing with 4 cores
*********************************
** Installing mpi_scheduler... **
*********************************
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /storage/plzen1/home/davidomartinez/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /storage/plzen1/home/davidomartinez/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /storage/plzen1/home/davidomartinez/miniconda3/lib/libmpi.so (found version "3.1")
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
    Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.

-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/build
Scanning dependencies of target mpi-scheduler
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/main.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Checkpoint.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/CommandsRunner.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Command.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Common.cpp.o
[ 50%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/DynamicLibrary.cpp.o
[ 58%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Instance.cpp.o
[ 75%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/ParallelImplementation.cpp.o
[ 75%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/RunStatistics.cpp.o
[ 83%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/SVGDrawer.cpp.o
[ 91%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/fork_implem/ForkImplem.cpp.o
/storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/src/ParallelImplementation.cpp: In member function 'void MPIScheduler::ParallelImplementation::startSlaves(int, char**)':
/storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/src/ParallelImplementation.cpp:100:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void*)argc;
            ^~~~
[100%] Linking CXX executable ../mpi-scheduler
/auto/plzen1/home/davidomartinez/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /storage/plzen1/home/davidomartinez/miniconda3/lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'
/auto/plzen1/home/davidomartinez/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /storage/plzen1/home/davidomartinez/miniconda3/lib/libstdc++.so: undefined reference to `clock_gettime@GLIBC_2.17'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mpi-scheduler.dir/build.make:253: mpi-scheduler] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: src/CMakeFiles/mpi-scheduler.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by BenoitMorel** [comment]
Dear davidomartinez,

Thanks for your kind feedback.

Regarding the conda installation, it might be an issue with your conda environment. To be sure, can you try installing any other conda package that is not already installed, and see if you get the same error message? 

Regarding the custom installation, cmake doesn't seem to find the C++ MPI installation. A possible workaround is:
`conda install openmpi-mpicc`
Even if you still have the issue after this command, can you send me the entire new output (I want to see if we still get ` -- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)`)

Best,
Benoit

**Comment by davidomartinez** [comment]
Hi Benoit:

Thank you for your quick answer. Still not working. I successfully installed the C ++ MPI, using the suggested command: conda install openmpi-mpicc. I guess that discards any issues with the functionality of my conda environment ...? After it, I still get the same error message when trying to install ParGenes through conda.
Likewise, it seems I still get the same error when installing manually (see below).
Cheers, 
DAVID

(base) (BUSTER)xxxx@xxx:~/ParGenes$ ./install.sh
Running from /storage/plzen1/home/davidomartinez/ParGenes
Installing with 4 cores
*********************************
** Installing mpi_scheduler... **
*********************************
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /storage/plzen1/home/davidomartinez/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /storage/plzen1/home/davidomartinez/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /storage/plzen1/home/davidomartinez/miniconda3/lib/libmpi.so (found version "3.1")
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
    Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.

-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/build
Scanning dependencies of target mpi-scheduler
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/main.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Command.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Checkpoint.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/CommandsRunner.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Common.cpp.o
[ 50%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/DynamicLibrary.cpp.o
[ 58%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/Instance.cpp.o
[ 66%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/ParallelImplementation.cpp.o
[ 75%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/RunStatistics.cpp.o
[ 83%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/SVGDrawer.cpp.o
[ 91%] Building CXX object src/CMakeFiles/mpi-scheduler.dir/fork_implem/ForkImplem.cpp.o
/storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/src/ParallelImplementation.cpp: In member function 'void MPIScheduler::ParallelImplementation::startSlaves(int, char**)':
/storage/plzen1/home/davidomartinez/ParGenes/MPIScheduler/src/ParallelImplementation.cpp:100:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void*)argc;
            ^~~~
[100%] Linking CXX executable ../mpi-scheduler
/auto/plzen1/home/davidomartinez/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /storage/plzen1/home/davidomartinez/miniconda3/lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'
/auto/plzen1/home/davidomartinez/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /storage/plzen1/home/davidomartinez/miniconda3/lib/libstdc++.so: undefined reference to `clock_gettime@GLIBC_2.17'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mpi-scheduler.dir/build.make:253: mpi-scheduler] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: src/CMakeFiles/mpi-scheduler.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by BenoitMorel** [comment]
Could you please:
- try installing any conda package that belongs to bioconda, so anything from this list: https://anaconda.org/bioconda/repo (I guess it will build properly, but I prefer being sure)
- give me your cmake version (`cmake --version`). In case it's 3.19, can you try downgrading to 3.18 with conda, and try installing ParGenes again (by running the uninstall.sh and then install.sh scripts), and send me the new output if it fails again.

**Comment by BenoitMorel** [comment]
And if the last two points do not change anything, could you also please give me the list of packages installed on your environment? (`conda list`)

**Comment by davidomartinez** [comment]
Thanks a lot, Benoit. Unfortunately, the suggested changes did not make it work. My version of cmake is 3.18.2. I am copying this here for the record but emailed you with more details.

**Comment by BenoitMorel** [comment]
Thanks David. Unfortunately I was not able to work on this today as promised.
But I had another idea. If that's not too much effort, could you please try to create a new conda environment, and to install ParGenes in this new empty environment?
Somehow this all seems to be about inconsistent dependencies, but it's hard to find out which one exactly...

**Comment by davidomartinez** [comment]
Hi Benoit: Thank you for this. I already tried that and it didn't work either. I decided to move forward and run it locally on my computer. It took some more time, but shorter than I expected and is already done. I hope this was just an uncommon issue with my particular conda installation and/or server. Thanks a lot again.

**Comment by BenoitMorel** [comment]
Hi David,
I am glad that the run finished ;-)
I close the issue, but please reopen it if you want/need to try to install ParGenes on your server again.
Best,
Benoit
