### ISSUE TITLE
Invalid taxon labels causes division by zero during parse run

### ISSUE THREAD

**Issue by pierrebarbera** [BenoitMorel/multi-raxml#64]
Example invalid taxon name:
```OTU_3747;56074372f84154d24af41b68ba2370a5f931dd4d;size=39546_2```

Thrown error during parsing phase of pargenes:
```
  Average number of taxa: 182
  Max number of taxa: 1481
  Average number of sites: 0
  Max number of sites: 0
[Error] <type 'exceptions.ZeroDivisionError'> integer division or modulo by zero
```

**Comment by lucaslima1618** [comment]
Hi,
I tried every possibility of taxon labeling, but the same error appears.

[Error] <type 'exceptions.ZeroDivisionError'> integer division or modulo by zero
Writing report file in /home/lucaslima/Documentos/Output8/report.txt
When reporting the issue, please always send us this file.


May you please help me?

Thanks in advance.

The report.txt follows

[report.txt](https://github.com/BenoitMorel/ParGenes/files/4439731/report.txt)

**Comment by BenoitMorel** [comment]
Hi Lucas,

Thanks for your report!

The report file says that ParGenes cannot find a file that should be installed by the installation script (`install.sh` in the top directory). Did you run this script before running ParGenes? If yes, could you please run it again and send me its output?

I will add a more explicit error message for this kind of issue :-)

Benoit

**Comment by lucaslima1618** [comment]
Hi Benoit, 

Thanks a lot for you help. You were right. I had a unnoted problem with the install.sh.

When I execute it the follow error apears: 

Could NOT find BISON (missing: BISON_EXECUTABLE) 
-- Could NOT find FLEX (missing: FLEX_EXECUTABLE) 
CMake Error at libs/pll-modules/libs/libpll/src/CMakeLists.txt:19 (BISON_TARGET):
  Unknown CMake command "BISON_TARGET".


-- Configuring incomplete, errors occurred!
See also "/home/lucaslima/ParGenes/raxml-ng/build/CMakeFiles/CMakeOutput.log".
See also "/home/lucaslima/ParGenes/raxml-ng/build/CMakeFiles/CMakeError.log".

The log files in attachment.

Cheers, 

[CMakeError.log](https://github.com/BenoitMorel/ParGenes/files/4441208/CMakeError.log)
[CMakeOutput.log](https://github.com/BenoitMorel/ParGenes/files/4441209/CMakeOutput.log)

**Comment by BenoitMorel** [comment]
It looks like you have some missing dependencies (flex and bison). See raxml-ng instructions to install them: https://github.com/amkozlov/raxml-ng#installation-instructions

If it still does not work, the best would be to directly ask in our raxml-ng google group: https://groups.google.com/forum/#!forum/raxml

Cheers,
Benoit

**Comment by BenoitMorel** [comment]
Hi Pierre, 

after 6 months of procrastination, I fixed this. I don't think I can really detect wrong taxon names from ParGenes (raxml-ng would have to do it), but I replaced the very obscure error message with something less confusing ;-)
