### ISSUE TITLE
Feature request: Add `--version` option

### ISSUE THREAD

**Issue by nylander** [BenoitMorel/multi-raxml#65]
Hi,

I suggest implementing a `--version` option in `arguments.py`.

Currently (both in branches master and dev, and in the latest release labeled "v.1.1.1"), there is a hardcoded string saying "PARGENES v1.0.1" when printing a header in `pargenescore.py`. The easily accessible `--version` (and/or `-v` etc) could be an easy reminder to keep the version string up to date.

Cheers
Johan

**Comment by BenoitMorel** [comment]
Dear Johan,

thanks for spotting the erroneous version label!
I will add a version option.
But I am not sure that this can prevent us from forgetting to update the version string: there is no way (as far as I know) to automatically check that the tag of the last git release and the version in the code correspond. If you have any suggestion, please let me know.

Cheers,
Benoit

**Comment by BenoitMorel** [comment]
Dear Johan,

I am closing the issue. Please reopen it if necessary.

Best,
Benoit
