### ISSUE TITLE
error:  thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by probstrodolfo** [BenoitMorel/multi-raxml#66]
Hi Benoit,

I am trying to install ParGenes in my lab server (OS X Yosemite 10.10.5) and I am getting the following error:

**In file included from /Users/longinolab/ParGenes/raxml-ng/src/common.h:23:
/Users/longinolab/ParGenes/raxml-ng/src/ParallelContext.hpp:89:10: error: 
      thread-local storage is not supported for the current target
  static thread_local size_t _thread_id;
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/raxml_module.dir/ICScoreCalculator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/CMakeFiles/raxml_module.dir/AncestralStates.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/raxml_module.dir/CommandLineParser.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/raxml_module.dir/Checkpoint.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/raxml_module.dir/all] Error 2
make: *** [all] Error 2**

I am not sure if it could be a bug on XCode. Should I try to build using clang instead? Appreciate any feedback.

**Comment by BenoitMorel** [comment]
Hi Probstrodolfo,

Could you please reopen the same issue in the raxml google group?
This looks like a raxml-ng compilation issue specific to OS X. You can try
with clang, but we should also fix this.

Benoit

Le ven. 26 juin 2020 à 07:03, probstrodolfo <notifications@github.com> a
écrit :

**Comment by probstrodolfo** [comment]
Hi Benoit,

Sure thing. Got it, thanks for the quick response. I will try it with clang then. 

Thanks,
