### ISSUE TITLE
Feature suggestion: add usage of astral-mp

### ISSUE THREAD

**Issue by nylander** [BenoitMorel/multi-raxml#68]
Dear @BenoitMorel 

thank you for the Pargenes package - very helpful tool.

A minor *feature request*: Would you consider adding support for running [ASTRAL-MP](https://github.com/smirarab/ASTRAL/tree/MP) to improve parallelization and decrease run times?

In principle, until the "MP" branch is merged with ASTRAL III master, one could perhaps add a `--astral_jar` argument (or `--astral-binay` to conform to the other arguments), and use that in combination with the `--astral-global-parameters` to accomplish the parallelization?

Cheers
Johan

**Comment by BenoitMorel** [comment]
Dear Johan,

Sure, this totally makes sense to have this option, especially if you want to run ParGenes+ASTRAL on many cores. I just added the `--astral-jar` argument. It is available on the master branch of ParGenes, but not on bioconda yet. If you need to have it on bioconda soon, I can push an intermediate release.

Please let me know if this option + the astral global parameters are enough to run ASTRAL-MP. 

Cheers,
Benoit

**Comment by nylander** [comment]
That's a great first step Benoit!
In addition, the authors of Astral recommends to explicitly specify the path to the astral lib as an argument to java: `-D"java.library.path=/path/to/astral/lib/"`. This would increase the speed x4 (according to the authors). As far as I can tell, such a command needs to be hard coded in pargenes and cannot simply be put in the argument file for astral. You already handle the astral lib in the pargenes installation, so the path would be easy to pick up.
Other than this, I think the relevant options for CPUs and GPUs can be left in the astral command file. Left for me or someone else to try!
Cheers
Johan

**Comment by BenoitMorel** [comment]
Dear Johan,
That's interesting, I didn't know that setting the `java.library.path` could make ASTRAL faster. I updated ParGenes to call ASTRAL accordingly. It should also work with the `--astral-jar` option. Many thanks for your suggestions!
Cheers,
Benoit

**Comment by BenoitMorel** [comment]
I am closing this issue. Please reopen it if there is something else I can do.
