### ISSUE TITLE
Optimizing branch length with fixed tree topology

### ISSUE THREAD

**Issue by LipengKang** [BenoitMorel/multi-raxml#70]
Hi Benoit,

Thanks for the well implementation of ParGenes.
I am using ParGenes to infer phylogenetic trees of genes for next hypothesis testing. Thus, It's better to fix the tree topology.
raxml-ng  can estimate the branch with a fixed tree topology like `raxml-ng --evaluate --msa prim.phy --threads 2 --model JC --tree T3.raxml.bestTree --prefix E1 `. 
In ParGenes, parameters `-R " --model --tree"`  and `-R " --model --tree-constraint"` can not result in bestTree with predefined topology. Meanwhile, ParGenes report fatal error using`-R " --model --evaluate --tree"` .

How to set parameters to infer phylogenetic trees  with  fixed topology in ParGenes?

Could you please give me some advice?

Thanks,
Lipeng

**Comment by BenoitMorel** [comment]
Hi Lipeng,

ParGenes was initially designed to run tree searches, and the `--evaluate` option probably conflicts with a search option. I am on vacations for the next two weeks and cannot properly fix this now, but maybe there is a quickfix:

In your pargenes installation, can you try commenting the 4 lines starting from: 
https://github.com/BenoitMorel/ParGenes/blob/master/pargenes/pargenes_src/raxml.py#L194
Don't forget to rollback if you need to perform "normal" searches.

Let me know if it works. If not, does ParGenes produce a report file (it should be written in the logs)? Can you send it to me? 

Best,
Benoit

**Comment by LipengKang** [comment]
Hi, Benoit,
parallel `raxml-ng --evaluate` was used as a replacement.
If the related function adds in pargenes, I am willing to give top priority.

Best,
Lipeng
