### ISSUE TITLE
export.py is missing

### ISSUE THREAD

**Issue by sav-che** [BenoitMorel/multi-raxml#72]
Dear Benoit Morel,

Wiki mentions [here](https://github.com/BenoitMorel/ParGenes/wiki/Exporting-relevant-files) a script [export.py](https://github.com/BenoitMorel/ParGenes/blob/master/pargenes/export.py) for simplified export, but the file seems to be missing.

Best,
Anton

**Comment by BenoitMorel** [comment]
Dear Anton,
Sorry for the late reply, I am on vacation. Thanks for the report, I'll fix
the link when I am back. It should be this file:
https://github.com/BenoitMorel/ParGenes/blob/master/pargenes/pargenes_src/export.py
Best
Benoit

Le mer. 28 déc. 2022, 10:55, Anton Savchenko ***@***.***> a
écrit :

**Comment by nylander** [comment]
URL is now corrected in the wiki
